version: '3'
services:
  eureka-svc:
    container_name: eureka-svc
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    environment:
      - EUREKA_SVC_HOST=eureka-svc
      - EUREKA_SVC_PORT=${EUREKA_SVC_PORT}
    ports:
      - "${EUREKA_SVC_PORT}:${EUREKA_SVC_PORT}"
    networks:
      - song_platform_network

  resource-svc:
    container_name: resource-svc
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    environment:
      - RESOURCE_SVC_PORT=${RESOURCE_SVC_PORT}
      - RESOURCE_DB_HOST=resource-svc-db
      - RESOURCE_DB_PORT=${RESOURCE_DB_SVC_PORT}
      - RESOURCE_DB_USERNAME=${RESOURCE_DB_USER}
      - RESOURCE_DB_PASSWORD=${RESOURCE_DB_PASS}
      - EUREKA_SVC_HOST=eureka-svc
      - EUREKA_SVC_PORT=${EUREKA_SVC_PORT}
      - EUREKA_PREFER_IP_ADDRESS=${EUREKA_PREFER_IP_ADDRESS}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - S3_AUDIO_BUCKET=${S3_AUDIO_BUCKET}
    ports:
      - "${RESOURCE_SVC_EXP_PORT}:${RESOURCE_SVC_PORT}"
    networks:
      - song_platform_network
    depends_on:
      - resource-svc-db
      - eureka-svc

  resource-svc-db:
    container_name: resource-svc-db
    image: postgres:12.19-alpine3.20
    environment:
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASS}
      POSTGRES_DB: resourcedb
    ports:
      - "${RESOURCE_DB_EXP_PORT}:${RESOURCE_DB_SVC_PORT}"
    networks:
      - song_platform_network
    volumes:
      - ./resource-service/init-db:/docker-entrypoint-initdb.d
      - resource-service-postgres-data:/var/lib/postgresql/data

  song-svc:
    image: song-service
    build:
      context: ./song-service
      dockerfile: Dockerfile
    environment:
      - SONG_SVC_PORT=${SONG_SVC_PORT}
      - SONG_DB_HOST=song-svc-db
      - SONG_DB_PORT=${SONG_DB_SVC_PORT}
      - SONG_DB_USERNAME=${SONG_DB_USER}
      - SONG_DB_PASSWORD=${SONG_DB_PASS}
      - EUREKA_SVC_HOST=eureka-svc
      - EUREKA_SVC_PORT=${EUREKA_SVC_PORT}
      - EUREKA_PREFER_IP_ADDRESS=${EUREKA_PREFER_IP_ADDRESS}
    ports:
      - "${SONG_SVC_EXP_PORT}:${SONG_SVC_PORT}"
    networks:
      - song_platform_network
    depends_on:
      - song-svc-db
      - eureka-svc
    deploy:
      replicas: 2

  song-svc-db:
    container_name: song-svc-db
    image: postgres:12.19-alpine3.20
    environment:
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASS}
      POSTGRES_DB: songdb
    ports:
      - "${SONG_DB_EXP_PORT}:${SONG_DB_SVC_PORT}"
    networks:
      - song_platform_network
    volumes:
      - ./song-service/init-db:/docker-entrypoint-initdb.d
      - song-service-postgres-data:/var/lib/postgresql/data

  processor-svc:
    container_name: processor-svc
    build:
      context: ./resource-processor
      dockerfile: Dockerfile
    environment:
      - PROCESSOR_SVC_PORT=${PROCESSOR_SVC_PORT}
    ports:
      - "${PROCESSOR_SVC_EXP_PORT}:${PROCESSOR_SVC_PORT}"
    networks:
      - song_platform_network

networks:
  song_platform_network:
    driver: bridge

volumes:
  song-service-postgres-data:
  resource-service-postgres-data:
