global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'eureka'
    eureka_sd_configs:
      - server: http://eureka-svc:8761/eureka
        refresh_interval: 30s

    relabel_configs:
      - source_labels: [ __meta_eureka_app_instance_metadata_prometheus_scrape ]
        regex: "true"
        action: keep

      - source_labels: [ __meta_eureka_app_instance_ip_addr, __meta_eureka_app_instance_metadata_prometheus_port ]
        separator: ":"
        target_label: __address__

      - source_labels: [ __meta_eureka_app_instance_metadata_prometheus_path ]
        target_label: __metrics_path__

      - source_labels: [ __meta_eureka_app_name ]
        target_label: job

      - source_labels: [ __meta_eureka_app_instance_id ]
        target_label: instance
