spring:
  application:
    name: resource-processor
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: ${MQ_CLIENT_PORT:5672}
    username: ${MQ_USER:guest}
    password: ${MQ_PASS:guest}
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: resource-processor
          group: ${QUEUE_NAME:resource-queue}
          consumer:
            max-attempts: 1
      rabbit:
        bindings:
          process-in-0:
            consumer:
              bindQueue: false
              declareExchange: false
              queueNameGroupOnly: true

server:
  port: ${PROCESSOR_SVC_PORT:8082}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SVC_HOST:localhost}:${EUREKA_SVC_PORT:8761}/eureka
  instance:
    preferIpAddress: ${EUREKA_PREFER_IP_ADDRESS:true}

resource-service-name: ${RESOURCE_SERVICE_NAME:resource-service}
song-service-name: ${SONG_SERVICE_NAME:song-service}


