spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONF_REPO:https://github.com/SaliiovM/song-platform-configuration}
          default-label: ${CONF_REPO_BRANCH:main}

server:
  port: ${CONF_SVC_PORT:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SVC_HOST:localhost}:${EUREKA_SVC_PORT:8761}/eureka
  instance:
    preferIpAddress: ${EUREKA_PREFER_IP_ADDRESS:true}
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": ${CONF_SVC_PORT:8888}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
