spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://${RESOURCE_DB_HOST:localhost}:${RESOURCE_DB_PORT:5432}/resourcedb
    username: ${RESOURCE_DB_USERNAME}
    password: ${RESOURCE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

song:
  base-url: http://${SONG_SVC_HOST:localhost}
  songs-endpoint: /songs

server:
  port: ${RESOURCE_SVC_PORT:8080}


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SVC_HOST:localhost}:${EUREKA_SVC_PORT:8761}/eureka
  instance:
    preferIpAddress: ${EUREKA_PREFER_IP_ADDRESS:true}
